import i18n from "i18next";
import { i18nextInitOptions } from "@/i18n/config";
import { I18nProvider } from "./i18nProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

i18n.init(i18nextInitOptions, (err) => {
  if (err) {
    console.error("i18next failed to initialize", err);
  }
});

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}) {
  i18n.changeLanguage(locale);
  return (
    <html lang={locale}>
      <body>
        <I18nProvider>{children}</I18nProvider>
      </body>
    </html>
  );
}
